### PR TITLE
TimeZone property always undefined in px-calendar-cell

### PR DESCRIPTION
**Pull request by benjaminliugang**
- In `px-calendar-cell.html`, we do not declare `timeZone` property. The `this.timeZone` value always is `undefined` when use in [_isPastTodaysDate](https://github.com/predixdesignsystem/px-calendar-picker/blob/master/px-calendar-cell.html#L244), [_isBeforeTodaysDate](https://github.com/predixdesignsystem/px-calendar-picker/blob/master/px-calendar-cell.html#L249), [_isTodaysDate](https://github.com/predixdesignsystem/px-calendar-picker/blob/master/px-calendar-cell.html#L254) methods.
- Fixed CI build failed issue(update the node version as 10.5.0)
- Fixed some failed unit tests(it seems the tests failed for a long time)

@joshsylvester, @benoitjchevalier , please help review.

### CODE REVIEW

**Comment by benjaminliugang** [comment]
@joshsylvester , could you help merge and release this fix?

**Comment by benjaminliugang** [comment]
@joshsylvester @GengGao , could you help me merge and release this fix?

**Comment by benjaminliugang** [comment]
Hi @joshsylvester , could you help me release this fix?

**Comment by justin-kirkwood** [comment]
@benjaminliugang I've released the fix v2.0.9

**Pull request merged**
